Repository ahmedheakl/decompilation, pull requests merged in 2023-10, with the labels that each got.

#1 Feature - Proprocessing
  decompile/preprossing/__init__.py
  decompile/preprossing/preprocess.py
  train.py
Labels: enhancement

#2 Feature - Standardization
  decompile/preprocessing/__init__.py
  decompile/preprocessing/preprocess.py
  decompile/preprocessing/standardize.py
  requirements-dev.txt
  requirements.txt
  tests/preprocessing/__init__.py
  tests/preprocessing/test_standardize.py
  tests/tests_data/preprocessing/standardize_test_input_1.s
  tests/tests_data/preprocessing/standardize_test_output_1.s
Labels: enhancement

#5 Feature - CI
  .github/workflows/test_pr.yml
  requirements-dev.txt
  scripts/linters_parser.py
  train.py
Labels: enhancement

#9 Feat - Assembly Generation
  .pylintrc
  decompile/preprocessing/preprocess.py
  preprocess_angha_dataset.py
Labels: bug, enhancement, help wanted

#10 Edit - Standardization Integration
  .gitignore
  decompile/preprocessing/preprocess.py
  decompile/preprocessing/standardize.py
  preprocess_angha_dataset.py
Labels: enhancement, help wanted

#11 Feat - Standardization Integration
  decompile/preprocessing/preprocess.py
  preprocess_angha_dataset.py
  scripts/comment_out_main_function.py
  scripts/delete_comments.py
Labels: enhancement
